name: Check links

on:
  schedule:
    - cron: '0 1 * * 4' # every Thursday, at 1AM
  workflow_dispatch:

jobs:
  check-links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
         go-version: 'stable'

      - name: Install Muffet
        run: |
          go install github.com/raviqqe/muffet/v2@latest

      - name: Run check links
        run: |
          make check-links
